name: dotnet package

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['7.0' ]

    steps:
      - uses: actions/checkout@v3
        
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Build
        run: dotnet build -c Release
              
      - name: Create package
        run: dotnet pack -c Release -o out
        
      - name: Nuget Publish
        run: dotnet nuget push ./out/*.nupkg --skip-duplicate --no-symbols -k ${{ secrets.NUGET_API_KEY }} -s "https://api.nuget.org/v3/index.json"
  